services:
  api1: &api
    image: ghcr.io/krymancer/rinha-de-backend-2026-ocaml:latest
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      INDEX_PATH: /app/index.bin
      FD_UDS: /sockets/api1.sock
      API_WARMUP_QUERIES: "8192"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "165M"

  api2:
    <<: *api
    environment:
      INDEX_PATH: /app/index.bin
      FD_UDS: /sockets/api2.sock
      API_WARMUP_QUERIES: "8192"

  lb:
    image: ghcr.io/krymancer/rinha-de-backend-2026-ocaml-lb:latest
    build:
      context: .
      dockerfile: Dockerfile.lb
    platform: linux/amd64
    ports: ["9999:9999"]
    environment:
      LB_PORT: "9999"
      API_SOCKETS: /sockets/api1.sock,/sockets/api2.sock
    volumes:
      - sockets:/sockets
    depends_on:
      api1: { condition: service_started }
      api2: { condition: service_started }
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "20M"

networks:
  default:
    driver: bridge

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m"
